# Destroy Terraform AKS Cluster Pipeline 

trigger: none




pool: Default

stages:
  - stage: plan_destroy
    jobs: 
      - job: plan_destroy
        pool: Default
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'terraform-aks-cluster-svc-conn'
            backendAzureRmResourceGroupName: 'terraform-storage-rg'
            backendAzureRmStorageAccountName: 'terraformstorage05'
            backendAzureRmContainerName: 'tfstatebackupfile'
            backendAzureRmKey: 'aks-prod.tfstate'

  - stage: destroy_env
    jobs: 
      - job: destroy_env
        pool: Default
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'terraform-aks-cluster-svc-conn'
            backendAzureRmResourceGroupName: 'terraform-storage-rg'
            backendAzureRmStorageAccountName: 'terraformstorage05'
            backendAzureRmContainerName: 'tfstatebackupfile'
            backendAzureRmKey: 'aks-prod.tfstate'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'terraform-aks-cluster-svc-conn'

  